"""Remove global email unique constraint

Revision ID: 1b12d7e1fb18
Revises: 30868a228fc3
Create Date: 2026-02-10 23:21:22.864407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b12d7e1fb18'
down_revision: Union[str, None] = '30868a228fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_tokens_token_id'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    op.drop_index(op.f('uq_users_global_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_global_username'), 'users', ['username'], unique=True)
    op.create_table('blacklisted_tokens',
    sa.Column('token_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('blacklisted_tokens_pkey'))
    )
    op.create_index(op.f('ix_blacklisted_tokens_token_id'), 'blacklisted_tokens', ['token_id'], unique=True)
    # ### end Alembic commands ###
