"""Initial migration

Revision ID: 8b155ab77dee
Revises: 
Create Date: 2026-02-08 17:21:45.742306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b155ab77dee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('SUPER_ADMIN', 'TENANT_ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_users_tenant_username')
    )
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shopping_lists_created_at', 'shopping_lists', ['created_at'], unique=False)
    op.create_index('idx_shopping_lists_owner_id', 'shopping_lists', ['owner_id'], unique=False)
    op.create_index('idx_shopping_lists_tenant_id', 'shopping_lists', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_created_at', 'chat_messages', ['shopping_list_id', 'created_at'], unique=False)
    op.create_index('idx_chat_sender_id', 'chat_messages', ['sender_id'], unique=False)
    op.create_index('idx_chat_shopping_list_id', 'chat_messages', ['shopping_list_id'], unique=False)
    op.create_table('items',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PURCHASED', name='item_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_added_by', 'items', ['added_by'], unique=False)
    op.create_index('idx_items_shopping_list', 'items', ['shopping_list_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shopping_list_id', sa.UUID(), nullable=True),
    sa.Column('type', postgresql.ENUM('LIST_INVITE', 'INVITE_ACCEPTED', 'INVITE_REJECTED', 'ITEM_ADDED', 'ITEM_PURCHASED', 'CHAT_MESSAGE', name='notification_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_type', 'notifications', ['user_id', 'type'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('shopping_list_members',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'MEMBER', name='member_role'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', name='member_status'), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_add_item', sa.Boolean(), nullable=False),
    sa.Column('can_update_item', sa.Boolean(), nullable=False),
    sa.Column('can_delete_item', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopping_list_id', 'user_id', name='uq_members_list_user')
    )
    op.create_index('idx_members_shopping_list_id', 'shopping_list_members', ['shopping_list_id'], unique=False)
    op.create_index('idx_members_status', 'shopping_list_members', ['status'], unique=False)
    op.create_index('idx_members_user_id', 'shopping_list_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_members_user_id', table_name='shopping_list_members')
    op.drop_index('idx_members_status', table_name='shopping_list_members')
    op.drop_index('idx_members_shopping_list_id', table_name='shopping_list_members')
    op.drop_table('shopping_list_members')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_items_shopping_list', table_name='items')
    op.drop_index('idx_items_added_by', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_chat_shopping_list_id', table_name='chat_messages')
    op.drop_index('idx_chat_sender_id', table_name='chat_messages')
    op.drop_index('idx_chat_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_shopping_lists_tenant_id', table_name='shopping_lists')
    op.drop_index('idx_shopping_lists_owner_id', table_name='shopping_lists')
    op.drop_index('idx_shopping_lists_created_at', table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
