"""Make tenant_id nullable for global super admins

Revision ID: a63b2b71610e
Revises: 8b155ab77dee
Create Date: 2026-02-08 17:49:03.859028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63b2b71610e'
down_revision: Union[str, None] = '8b155ab77dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
