"""add_blacklisted_tokens_table

Revision ID: c8ff3458bced
Revises: a63b2b71610e
Create Date: 2026-02-10 18:48:40.114214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8ff3458bced'
down_revision: Union[str, None] = 'a63b2b71610e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_tokens_token_id'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    op.alter_column('shopping_list_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_members_status'), table_name='shopping_list_members')
    op.drop_column('shopping_list_members', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_members', sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', name='member_status'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_members_status'), 'shopping_list_members', ['status'], unique=False)
    op.alter_column('shopping_list_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_table('blacklisted_tokens',
    sa.Column('token_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('blacklisted_tokens_pkey'))
    )
    op.create_index(op.f('ix_blacklisted_tokens_token_id'), 'blacklisted_tokens', ['token_id'], unique=True)
    # ### end Alembic commands ###
